Unity clean pr
inworld-ai/inworld-ndk pull request #11
Opened 2023-06-23 15:18 UTC by Div-Inworld

2023-06-23 15:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/inworld-ai/inworld-ndk?pullRequest=11) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/inworld-ai/inworld-ndk?pullRequest=11) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: art-vozniuk<br/>:x: Div-Inworld<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/inworld-ai/inworld-ndk?pullRequest=11) it.</sub>

2023-07-20 16:07 UTC, art-vozniuk requested changes

2023-07-20 16:07 UTC, art-vozniuk commented on Unity_NDK/client_wrapper.cpp
> +        bool result = wrapper->client.GetConnectionError(errorMessage, errorCode);
do early return if false

2023-07-20 21:46 UTC, Div-Inworld commented on src/Packets.cpp
> +        Proto.mutable_data_chunk()->set_chunk(_Chunk);
> call DataEvent::ToProtoInternal insdead of copy

does not work. the audio breaks completely

2023-07-21 11:56 UTC, art-vozniuk requested changes

2023-07-21 11:56 UTC, art-vozniuk commented on Example/Unity_NDK/client_wrapper.cpp
> +            cppUtteranceIds.emplace_back(std::string(UtteranceIds[i]));
should be cppUtteranceIds.emplace_back(UtteranceIds[i]);
you call emplace to forward char* to a string constructor that will be callled inside. the way it's now constructor will be called twice

2023-07-21 13:15 UTC, Div-Inworld commented on src/Utils/Log.h
> +	void stdLog(std::string fmt);
it is needed, i invoke it with a preprocessor now for debugging primarily. Any Logs or warnings from the NDK are now invoking this when the UNITY_NDK preprocessor is set so that way all the logs, warnings and errors show up in the editor log

2023-07-21 13:44 UTC, art-vozniuk requested changes

2023-07-21 13:44 UTC, art-vozniuk commented on src/Utils/Log.h
> +#include <iostream>
should be in #if UNITY macro and move it into #else above pls

2023-07-21 13:44 UTC, art-vozniuk commented on src/Utils/Log.h
> +	void stdLog(std::string fmt);
lets just call std::cout << fmt << std::endl instead. let's remove the function, stdLog is a weird name and you will not have to use stringstream in the code lower

2023-07-21 13:44 UTC, art-vozniuk commented on src/Utils/Log.h
> +  #if UNITY_NDK
fix tabs here pls, should on the same column as #if ANDROID lower

2023-07-21 13:44 UTC, art-vozniuk commented on src/Utils/Log.h
> +  #if UNITY_NDK
also tabs

2023-07-21 13:44 UTC, art-vozniuk commented on src/Utils/Log.h
> +		std::ostringstream ss;
get rid of stringstream, just cout << ... <<  ... etc. also no need to call .c_str (), << operator should be overloaded for std::string

2023-07-21 15:11 UTC, Div-Inworld commented on Unity_NDK/client_wrapper.cpp
> +        if(options.has_capabilities())
added log to notify capabilities not set

2023-07-21 16:24 UTC, art-vozniuk approved these changes

2023-07-21 17:04 UTC, merged