Callback for Unity to receive session token for continuity
inworld-ai/inworld-ndk pull request #30
Opened 2023-08-23 19:43 UTC by Div-Inworld

2023-08-24 13:59 UTC, art-vozniuk requested changes

2023-08-24 13:59 UTC, art-vozniuk commented on src/Client.h
> +		std::function<void(SessionInfo)> UnitySessionTokenCallback;
after token is generated, it's cached in SessionInfo field. it seems like you just need a getter for it. let's discuss

2023-08-28 05:23 UTC, Div-Inworld commented on src/Client.h
> +		std::function<void(SessionInfo)> UnitySessionTokenCallback;
Implemented refactor, added getter leveraging GenerateToken callback and removing ifdefs

2023-08-28 10:43 UTC, art-vozniuk requested changes

2023-08-28 10:43 UTC, art-vozniuk commented on Example/Unity/client_wrapper.cpp
> +                auto info = wrapper->client.GetSessionInfo();
const auto& info = .... to avoid copy

2023-08-28 10:43 UTC, art-vozniuk commented on src/Client.h
> +		SessionInfo GetSessionInfo();
const SessionInfo& GetSessionInfo() const

2023-08-28 10:43 UTC, art-vozniuk commented on src/Client.h
> +		void SetOptions(ClientOptions options);
void SetOptions(const ClientOptions& Options);

and move both of methods lower, to the end of public section please

2023-08-28 10:43 UTC, art-vozniuk commented on Example/Unity/client_wrapper.cpp
> +    void HandleAgentInfos(const std::vector<Inworld::AgentInfo>& AgentInfos, LoadSceneCallbackType LoadSceneCallback) {
if it's used only in this cpp file then
static void Handle...

2023-08-28 13:30 UTC, art-vozniuk commented on src/Client.h
> +		void SetOptions(ClientOptions options);
you didn't fix void SetOptions(const ClientOptions& Options);

2023-08-28 13:43 UTC, art-vozniuk approved these changes

2023-08-28 23:19 UTC, merged